plugins:

  dblb:
    executor: central_deployment_agent
    package_name: cloudify-dblb
    package_version: '0.1'
    source: https://github.com/EarthmanT/cloudify-dblb/archive/master.zip

workflows:

  scale_and_update:
    mapping: dblb.cloudify_dblb.tasks.scale_and_update
    parameters:
      db_deployment_id:
        default: 'db'
      lb_deployment_id:
        default: 'lb'
      scale_parameters:
        default: {'scalable_entity_name': 'app_group'}
